name: Pillar >10

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: AndrzejProchyra/BookBuilderDashboard/.github/workflows/main.yml@make-texlive-release-a-parameter
    with:
      bookname: BuildingUIWithSpec
      texlive_release: '2026'
